routes/web.php
    Route::get('get-incremented-deduction', [App\Http\Controllers\Admin\Employee\DeductionIncrementController::class, 'getIncrementedDeduction'])
        ->name('get-incremented-deduction');

    // DA Differance
    Route::resource('da-differance', App\Http\Controllers\Admin\Employee\DADifferanceController::class);
    Route::get('fetch-current-da', [App\Http\Controllers\Admin\Employee\DADifferanceController::class, 'fetchCurrentDA'])->name('fetch-current-da');



    // End Salary Structure


    // Employee Loans / LIC /Festival Advance Start
    Route::resource('employee-loans', App\Http\Controllers\Admin\Employee\EmployeeLoanController::class);
    Route::post('employee-loan-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Employee\EmployeeLoanController::class, 'employeeLoanStatus'])->name('employee-loan-status');

    Route::resource('employee-monthly-loans', App\Http\Controllers\Admin\Employee\EmployeeMonthlyLoanController::class);
    Route::get('employee-monthly-loans/{from_date}/{to_date}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyLoanController::class, 'showEmployeeLoans'])->name('employee-monthly-loans.showEmployeeLoans');
    Route::post('employee-monthly-loan-status/{model_id}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyLoanController::class, 'employeeMonthlyLoanStatus'])->name('employee-monthly-loan-status');

    Route::resource('yearly-bonus', App\Http\Controllers\Admin\Employee\YearlyBonusController::class);
    Route::get('fetch-emp-details/{Emp_Code}', [App\Http\Controllers\Admin\Employee\YearlyBonusController::class, 'fetchEmployeeDetails'])->name('fetch-emp-details');
    
    // LIC
    Route::resource('lic-dedcution', App\Http\Controllers\Admin\Employee\LICDeductionController::class);
    Route::post('employee-lic-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Employee\LICDeductionController::class, 'employeeLicStatus'])->name('employee-lic-status');

    Route::resource('employee-monthly-lic', App\Http\Controllers\Admin\Employee\EmployeeMonthlyLicController::class);
    Route::get('employee-monthly-lic/{from_date}/{to_date}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyLicController::class, 'showEmployeeLic'])->name('employee-monthly-lic.showEmployeeLic');
    Route::post('employee-monthly-lic-status/{model_id}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyLicController::class, 'employeeMonthlyLicStatus'])->name('employee-monthly-lic-status');

    // Festival Advance
    Route::resource('employee-festival-advance', App\Http\Controllers\Admin\Employee\EmployeeFestivalAdvanceController::class);
    Route::get('fetch-date-range-festival-advance/{month}', [App\Http\Controllers\Admin\Employee\EmployeeFestivalAdvanceController::class, 'fetchDateRange'])
    ->name('fetch-date-range-festival-advance');

    Route::resource('monthly-festivalAdvance', App\Http\Controllers\Admin\Employee\EmployeeMonthlyFestivalController::class);
    Route::get('monthly-festival-advance/{from_date}/{to_date}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyFestivalController::class, 'showEmployeeFestivalAdvance'])->name('monthly-festival-advance');
    Route::post('monthly-festivalAdvance-status/{model_id}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyFestivalController::class, 'monthlyFestivalAdvanceStatus'])->name('monthly-festivalAdvance-status');

    // Employee Loans / LIC / Festival Advance End

    // Attendance Managament
    Route::resource('add-absent', App\Http\Controllers\Admin\Attendance\EmployeeAbsent::class);
    Route::get('fetch-attendance-details/{Emp_Code}/{month}', [App\Http\Controllers\Admin\Attendance\EmployeeAbsent::class, 'fetchAttendanceDetails'])
    ->name('fetch-attendance-details');

    Route::resource('add-leave', App\Http\Controllers\Admin\Attendance\AddEmployeeLeaveController::class);
    Route::get('fetch-employee-details-leave/{Emp_Code}/{month}', [App\Http\Controllers\Admin\Attendance\AddEmployeeLeaveController::class, 'fetchEmployeeDetails'])
    ->name('fetch-employee-details-leave');

    Route::resource('leave-approval', App\Http\Controllers\Admin\Attendance\LeaveApprovalController::class);
    Route::get('approve-leave/{id}', [App\Http\Controllers\Admin\Attendance\LeaveApprovalController::class, 'ApproveLeave'])
    ->name('approve-leave');
    // End Attendance Management

    // Freeze Attendance
    Route::resource('freeze-attendance', App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class);
    Route::get('employee-monthly-salary/{from_date}/{to_date}', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'showEmployeeSalary'])->name('employee-monthly-salary.showEmployeeSalary');
    Route::get('unfreeze-employee', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'unfreezeEmployee'])->name('unfreeze-employee');
    Route::get('freeze-employee', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'freezeEmployee'])->name('freeze-employee');

    Route::get('fetch-date-range/{month}', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'fetchDateRange'])
        ->name('fetch-date-range');
    // Freeze Attendance End

    // Supplimentary Bill
    Route::resource('supplimentary-bill', App\Http\Controllers\Admin\Employee\SupplimentaryController::class);
    Route::get('fetch-employee-details-supplimentary/{Emp_Code}', [App\Http\Controllers\Admin\Employee\SupplimentaryController::class, 'fetchEmployeeDetails'])
        ->name('fetch-employee-details-supplimentary');
    Route::resource('suspend-supplimentary-bill', App\Http\Controllers\Admin\Employee\SuspendSupplimentaryController::class);
    Route::post('select-supplimentary-bill-no-of-days', [App\Http\Controllers\Admin\Employee\SupplimentaryController::class, 'fetchSupplimentaryBillNoofDays'])->name('select-supplimentary-bill-no-of-days');

    // Reports Start
    Route::resource('bank-statement', App\Http\Controllers\Admin\Report\BankStatementController::class);
    Route::resource('pay-sheet', App\Http\Controllers\Admin\Report\PaySheetController::class);
    Route::get('pay-sheet-pdf', [App\Http\Controllers\Admin\Report\PaySheetController::class, 'showPaySheetPDF'])->name('pay-sheet-pdf');


    Route::resource('bank-deduction-employee-report', App\Http\Controllers\Admin\Report\BankDeductionEmployeeController::class);
    Route::resource('bank-deduction-report', App\Http\Controllers\Admin\Report\BankDeductionController::class);
    Route::resource('summary-department-report', App\Http\Controllers\Admin\Report\GrandSummaryDepartmentController::class);
    Route::get('grand-summary-department-pdf', [App\Http\Controllers\Admin\Report\GrandSummaryDepartmentController::class, 'showGrandSummaryDepartmentPDF'])->name('grand-summary-department-pdf');
    Route::resource('summary-ward-report', App\Http\Controllers\Admin\Report\GrandSummaryWardController::class);
    Route::get('grand-summary-ward-pdf', [App\Http\Controllers\Admin\Report\GrandSummaryWardController::class, 'showGrandSummaryWardPDF'])->name('grand-summary-ward-pdf');
    Route::resource('summary-report', App\Http\Controllers\Admin\Report\GrandSummaryController::class);
    Route::get('grand-summary-pdf', [App\Http\Controllers\Admin\Report\GrandSummaryController::class, 'showGrandSummaryPDF'])->name('grand-summary-pdf');
    Route::resource('pay-sheet-excel', App\Http\Controllers\Admin\Report\PaySheetExcelController::class);

    Route::resource('allowance-report', App\Http\Controllers\Admin\Report\AllowanceReportController::class);
    Route::resource('deduction-report', App\Http\Controllers\Admin\Report\DeductionReportController::class);

    Route::resource('retirement-report', App\Http\Controllers\Admin\Report\RetirementController::class);
    // Reports End


    // Pension Start
    Route::resource('pension', App\Http\Controllers\Admin\Pension\PensionController::class);
    Route::resource('freeze-pension', App\Http\Controllers\Admin\Pension\FreezePensionController::class);
    Route::get('pensioner-bill-pdf/{month}/{from_date}/{to_date}', [App\Http\Controllers\Admin\Pension\FreezePensionController::class, 'showPensionerBillPDF'])->name('pensioner-bill-pdf');
    Route::resource('pensioner-bill', App\Http\Controllers\Admin\Pension\PensionerBillController::class);
    Route::get('pensioner-bill-bank-pdf', [App\Http\Controllers\Admin\Pension\PensionerBillController::class, 'showPensionerBillPDF'])->name('pensioner-bill-bank-pdf');
    Route::resource('pension-bank-statement', App\Http\Controllers\Admin\Pension\BankStatementController::class);
    Route::resource('grand-total-pensioner', App\Http\Controllers\Admin\Pension\GrandTotalPensionerController::class);
    Route::get('grand-total-pdf', [App\Http\Controllers\Admin\Pension\GrandTotalPensionerController::class, 'showGrandTotalPensionerPDF'])->name('grand-total-pdf');

    // Pension End


    // PF Start
    Route::resource('pf-opening-balance', App\Http\Controllers\Admin\PF\PFOpeningController::class);
    Route::resource('pf-department-loan', App\Http\Controllers\Admin\PF\PFDepartmentLoan::class);
    Route::get('fetch-employee-details-pf/{pf_no}', [App\Http\Controllers\Admin\PF\PFDepartmentLoan::class, 'fetchEmployeeDetails'])
        ->name('fetch-employee-details-pf');

    Route::resource('generate-pf-report', App\Http\Controllers\Admin\PF\GeneratePFReport::class);
    Route::resource('pf-report', App\Http\Controllers\Admin\PF\PFReport::class);
    Route::resource('pf-closing', App\Http\Controllers\Admin\PF\PFClosing::class);


    // PF End

    // Service book start
    Route::get('service-book-pdf', [App\Http\Controllers\Admin\ServiceBook\ServiceBookController::class, 'showServiceBookPDF'])->name('service-book-pdf');
    Route::get('tax-calculation', [App\Http\Controllers\Admin\TaxCalculation\TaxCalculationController::class, 'showCalculationForm'])->name('tax-calculation');

app/Models/Attendance.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Attendance extends BaseModel
{
    use HasFactory, SoftDeletes;

    protected $fillable = ['employee_id', 'Emp_Code', 'emp_name', 'from_date', 'to_date', 'main_present_days', 'total_present_days' , 'total_absent_days' , 'total_leave', 'total_half_days', 'month', 'financial_year_id'];

    public static function booted()
    {
        static::created(function (self $user)
        {
            if(Auth::check())
            {
                self::where('id', $user->id)->update([
                    'created_by'=> Auth::user()->id,
                ]);
            }
        });
        static::updated(function (self $user)
        {
            if(Auth::check())
            {
                self::where('id', $user->id)->update([
                    'updated_by'=> Auth::user()->id,
                ]);
            }
        });
        static::deleting(function (self $user)
        {
            if(Auth::check())
            {
                self::where('id', $user->id)->update([
                    'deleted_by'=> Auth::user()->id,
                ]);
            }
        });
    }
}

app/Http/Controllers/Admin/Attendance/EmployeeAbsent.php
<?php

namespace App\Http\Controllers\Admin\Attendance;

use App\Http\Controllers\Admin\Controller;
use App\Http\Requests\Admin\Attendance\StoreAbsentAttendanceRequest;
use App\Models\Attendance;
use App\Models\Employee;
use App\Models\FinancialYear;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class EmployeeAbsent extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('admin.attendance.add-absent-attendance');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreAbsentAttendanceRequest $request)
    {

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(StoreAbsentAttendanceRequest $request, $id)
    {
        $attendance = Attendance::where('id',$id)->first();

        try {
            DB::beginTransaction();
            $input = $request->validated();
            $attendance->update(Arr::only($input, Attendance::getFillables()));
            DB::commit();
            return response()->json(['success' => 'Attendnce updated successfully!']);
        } catch (\Exception $e) {
            return $this->respondWithAjax($e, 'updating', 'Attendnce');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }

    public function fetchAttendanceDetails($emp_id, $month)
    {
        $authUser = Auth::user();

        // Fetch employee details with necessary conditions
        $employee_details = Employee::with('ward', 'department', 'designation', 'class')
            ->where('employee_id', $emp_id)
            ->when($authUser->hasRole('Ward HOD'), function ($query) use ($authUser) {
                return $query->where('ward_id', $authUser->ward_id);
            })
            ->when($authUser->hasRole('Department HOD'), function ($query) use ($authUser) {
                return $query->where('department_id', $authUser->department_id);
            })
            ->whereNotExists(function ($query) use ($emp_id) {
                $query->select(DB::raw(1))
                    ->from('employee_statuses')
                    ->whereColumn('employee_statuses.employee_id', 'employees.id')
                    ->where('employee_statuses.Emp_Code', $emp_id)
                    ->whereNull('employee_statuses.deleted_at');
            })
            ->select('id', 'fname', 'mname', 'lname', 'ward_id', 'department_id', 'clas_id', 'designation_id', 'pf_account_no')
            ->first();

        // Fetch active financial year
        $fy_id = session('financial_year');

        $financial_year = FinancialYear::where('id', $fy_id)->first();
        if ($financial_year) {


            $year = ($month <= 3) ? date('Y', strtotime($financial_year->to_date)) : date('Y', strtotime($financial_year->from_date));
            $fromDate = Carbon::parse("$year-$month-16")->startOfMonth()->toDateString();
            $toDate = Carbon::parse("$year-$month-16")->endOfMonth()->toDateString();

            // Fetch attendance details
            $attendance_details = Attendance::where('Emp_Code', $emp_id)
                ->where('from_date', $fromDate)
                ->where('to_date', $toDate)
                ->first();


        } else {
            $attendance_details = null;
        }

        if ($employee_details && $attendance_details) {

            $response = [
                'result'                => 1,
                'employee_details'      => $employee_details,
                'attendance_details'    => $attendance_details,
            ];
        } else {
            $response = [
                'result' => 0,
                'message' => 'Employee details or attendance details not found.'
            ];
        }

        return response()->json($response);
    }

}

resources/views/admin/attendance/pending-employee-leave.blade.php
<x-admin.layout>
    <x-slot name="title">Pending Employee Leave</x-slot>
    <x-slot name="heading">Pending Employee Leave</x-slot>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="buttons-datatables" class="table table-bordered nowrap align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Sr No.</th>
                                    <th>Employee Id</th>
                                    <th>Leave</th>
                                    <th>From Date</th>
                                    <th>To Date</th>
                                    <th>Rejoin Date</th>
                                    <th>No. of Days</th>
                                    <th>Remark</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($employee_leaves as $employee_leave)
                                        @if ($employee_leave->status == 1)
                                            @php $status = 'Approved'; @endphp
                                        @elseif ($employee_leave->status == 2)
                                            @php $status = 'Rejected'; @endphp
                                        @else
                                            @php $status = 'Pending'; @endphp
                                        @endif

                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $employee_leave?->Emp_Code }}</td>
                                        <td>{{ $employee_leave?->leaveType?->name }}</td>
                                        <td>{{ $employee_leave?->from_date }}</td>
                                        <td>{{ $employee_leave?->to_date }}</td>
                                        <td>{{ $employee_leave?->rejoin_date }}</td>
                                        <td>{{ $employee_leave?->no_of_days }}</td>
                                        <td>{{ $employee_leave?->remark }}</td>
                                        <td>{{ $status }}</td>
                                        <td>
                                            @can('leave-approval.approve')
                                                <button class="edit-element btn btn-secondary px-2 py-1" title="Approve Leave" data-id="{{ $employee_leave->id }}"><i data-feather="check"></i></button>
                                            @endcan
                                            @can('leave-approval.reject')
                                                <button class="btn btn-danger rem-element px-2 py-1" title="Reject Leave" data-id="{{ $employee_leave->id }}"><i data-feather="x"></i> </button>
                                            @endcan
                                        </td>
                                    </tr>
                                @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="zoomInModal" class="modal fade zoomIn" tabindex="-1" aria-labelledby="zoomInModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="zoomInModalLabel">Reject Remark</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST" id="editForm">
                        @csrf
                        <div class="mb-3 row">
                            <input type="hidden" name="edit_model_id" id="edit_model_id">
                            <div class="col-md-12 mt-2">
                                <label class="col-form-label" for="remark">Remark<span class="text-danger">*</span></label>
                                <textarea class="form-control" name="remark" id="remark"></textarea>
                                <span class="text-danger invalid Emp_Code_err"></span>
                            </div>

                        </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Submit</button>
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

</x-admin.layout>

<!-- Delete -->
<script>

    $("#buttons-datatables").on("click", ".edit-element", function(e) {
        e.preventDefault();
        swal({
                title: "Are you sure to approve this Leave?",
                icon: "info",
                buttons: ["Cancel", "Confirm"]
            })
            .then((justTransfer) => {
                if (justTransfer) {

                    var model_id = $(this).attr("data-id");
                    var url = "{{ route('approve-leave', ':model_id') }}";

                    $.ajax({
                        url: url.replace(':model_id', model_id),
                        type: 'GET',
                        success: function(data, textStatus, jqXHR) {
                            if (!data.error && !data.error2) {
                                swal("Success!", data.success, "success")
                                    .then((action) => {
                                        window.location.reload();
                                    });
                            } else {
                                if (data.error) {
                                    swal("Error!", data.error, "error");
                                } else {
                                    swal("Error!", data.error2, "error");
                                }
                            }
                        },
                        error: function(error, jqXHR, textStatus, errorThrown) {
                            swal("Error!", "Something went wrong", "error");
                        },
                    });
                }
            });
    });

    $("#buttons-datatables").on("click", ".rem-element", function(e) {
        e.preventDefault();
        swal({
                title: "Are you sure to reject this Leave?",
                icon: "info",
                buttons: ["Cancel", "Confirm"]
            })
            .then((justTransfer) => {
                if (justTransfer) {

                    $('#zoomInModal').modal('show');
                    $('#edit_model_id').val($(this).attr("data-id"));
                }
            });
    });

    $(document).ready(function() {
        $("#editForm").submit(function(e) {
            e.preventDefault();
            $("#editSubmit").prop('disabled', true);
            var formdata = new FormData(this);
            formdata.append('_method', 'PUT');
            var model_id = $('#edit_model_id').val();
            var url = "{{ route('leave-approval.update', ':model_id') }}";
            //
            $.ajax({
                url: url.replace(':model_id', model_id),
                type: 'POST',
                data: formdata,
                contentType: false,
                processData: false,
                success: function(data) {
                    $("#editSubmit").prop('disabled', false);
                    if (!data.error2)
                        swal("Successful!", data.success, "success")
                        .then((action) => {
                            window.location.href = '{{ route('leave-approval.index') }}';
                        });
                    else
                        swal("Error!", data.error2, "error");
                },
                statusCode: {
                    422: function(responseObject, textStatus, jqXHR) {
                        $("#editSubmit").prop('disabled', false);
                        resetErrors();
                        printErrMsg(responseObject.responseJSON.errors);
                    },
                    500: function(responseObject, textStatus, errorThrown) {
                        $("#editSubmit").prop('disabled', false);
                        swal("Error occured!", "Something went wrong please try again", "error");
                    }
                }
            });

        });
    });

</script>