routes/web.php
    Route::get('fetch-emp-details/{Emp_Code}', [App\Http\Controllers\Admin\Employee\YearlyBonusController::class, 'fetchEmployeeDetails'])->name('fetch-emp-details');
    
    // LIC
    Route::resource('lic-dedcution', App\Http\Controllers\Admin\Employee\LICDeductionController::class);
    Route::post('employee-lic-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Employee\LICDeductionController::class, 'employeeLicStatus'])->name('employee-lic-status');

    Route::resource('employee-monthly-lic', App\Http\Controllers\Admin\Employee\EmployeeMonthlyLicController::class);
    Route::get('employee-monthly-lic/{from_date}/{to_date}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyLicController::class, 'showEmployeeLic'])->name('employee-monthly-lic.showEmployeeLic');
    Route::post('employee-monthly-lic-status/{model_id}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyLicController::class, 'employeeMonthlyLicStatus'])->name('employee-monthly-lic-status');

    // Festival Advance
    Route::resource('employee-festival-advance', App\Http\Controllers\Admin\Employee\EmployeeFestivalAdvanceController::class);
    Route::get('fetch-date-range-festival-advance/{month}', [App\Http\Controllers\Admin\Employee\EmployeeFestivalAdvanceController::class, 'fetchDateRange'])
    ->name('fetch-date-range-festival-advance');

    Route::resource('monthly-festivalAdvance', App\Http\Controllers\Admin\Employee\EmployeeMonthlyFestivalController::class);
    Route::get('monthly-festival-advance/{from_date}/{to_date}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyFestivalController::class, 'showEmployeeFestivalAdvance'])->name('monthly-festival-advance');
    Route::post('monthly-festivalAdvance-status/{model_id}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyFestivalController::class, 'monthlyFestivalAdvanceStatus'])->name('monthly-festivalAdvance-status');

    // Employee Loans / LIC / Festival Advance End

    // Attendance Managament
    Route::resource('add-absent', App\Http\Controllers\Admin\Attendance\EmployeeAbsent::class);
    Route::get('fetch-attendance-details/{Emp_Code}/{month}', [App\Http\Controllers\Admin\Attendance\EmployeeAbsent::class, 'fetchAttendanceDetails'])
    ->name('fetch-attendance-details');

    Route::resource('add-leave', App\Http\Controllers\Admin\Attendance\AddEmployeeLeaveController::class);
    Route::get('fetch-employee-details-leave/{Emp_Code}/{month}', [App\Http\Controllers\Admin\Attendance\AddEmployeeLeaveController::class, 'fetchEmployeeDetails'])
    ->name('fetch-employee-details-leave');

    Route::resource('leave-approval', App\Http\Controllers\Admin\Attendance\LeaveApprovalController::class);
    Route::get('approve-leave/{id}', [App\Http\Controllers\Admin\Attendance\LeaveApprovalController::class, 'ApproveLeave'])
    ->name('approve-leave');
    // End Attendance Management

    // Freeze Attendance
    Route::resource('freeze-attendance', App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class);
    Route::get('employee-monthly-salary/{from_date}/{to_date}', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'showEmployeeSalary'])->name('employee-monthly-salary.showEmployeeSalary');
    Route::get('unfreeze-employee', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'unfreezeEmployee'])->name('unfreeze-employee');
    Route::get('freeze-employee', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'freezeEmployee'])->name('freeze-employee');

    Route::get('fetch-date-range/{month}', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'fetchDateRange'])
        ->name('fetch-date-range');
    // Freeze Attendance End

    // Supplimentary Bill
    Route::resource('supplimentary-bill', App\Http\Controllers\Admin\Employee\SupplimentaryController::class);
    Route::get('fetch-employee-details-supplimentary/{Emp_Code}', [App\Http\Controllers\Admin\Employee\SupplimentaryController::class, 'fetchEmployeeDetails'])
        ->name('fetch-employee-details-supplimentary');
    Route::resource('suspend-supplimentary-bill', App\Http\Controllers\Admin\Employee\SuspendSupplimentaryController::class);
    Route::post('select-supplimentary-bill-no-of-days', [App\Http\Controllers\Admin\Employee\SupplimentaryController::class, 'fetchSupplimentaryBillNoofDays'])->name('select-supplimentary-bill-no-of-days');

    // Reports Start
    Route::resource('bank-statement', App\Http\Controllers\Admin\Report\BankStatementController::class);
    Route::resource('pay-sheet', App\Http\Controllers\Admin\Report\PaySheetController::class);
    Route::get('pay-sheet-pdf', [App\Http\Controllers\Admin\Report\PaySheetController::class, 'showPaySheetPDF'])->name('pay-sheet-pdf');


    Route::resource('bank-deduction-employee-report', App\Http\Controllers\Admin\Report\BankDeductionEmployeeController::class);
    Route::resource('bank-deduction-report', App\Http\Controllers\Admin\Report\BankDeductionController::class);
    Route::resource('summary-department-report', App\Http\Controllers\Admin\Report\GrandSummaryDepartmentController::class);
    Route::get('grand-summary-department-pdf', [App\Http\Controllers\Admin\Report\GrandSummaryDepartmentController::class, 'showGrandSummaryDepartmentPDF'])->name('grand-summary-department-pdf');
    Route::resource('summary-ward-report', App\Http\Controllers\Admin\Report\GrandSummaryWardController::class);
    Route::get('grand-summary-ward-pdf', [App\Http\Controllers\Admin\Report\GrandSummaryWardController::class, 'showGrandSummaryWardPDF'])->name('grand-summary-ward-pdf');
    Route::resource('summary-report', App\Http\Controllers\Admin\Report\GrandSummaryController::class);
    Route::get('grand-summary-pdf', [App\Http\Controllers\Admin\Report\GrandSummaryController::class, 'showGrandSummaryPDF'])->name('grand-summary-pdf');
    Route::resource('pay-sheet-excel', App\Http\Controllers\Admin\Report\PaySheetExcelController::class);

    Route::resource('allowance-report', App\Http\Controllers\Admin\Report\AllowanceReportController::class);
    Route::resource('deduction-report', App\Http\Controllers\Admin\Report\DeductionReportController::class);

    Route::resource('retirement-report', App\Http\Controllers\Admin\Report\RetirementController::class);
    // Reports End


    // Pension Start
    Route::resource('pension', App\Http\Controllers\Admin\Pension\PensionController::class);
    Route::resource('freeze-pension', App\Http\Controllers\Admin\Pension\FreezePensionController::class);
    Route::get('pensioner-bill-pdf/{month}/{from_date}/{to_date}', [App\Http\Controllers\Admin\Pension\FreezePensionController::class, 'showPensionerBillPDF'])->name('pensioner-bill-pdf');
    Route::resource('pensioner-bill', App\Http\Controllers\Admin\Pension\PensionerBillController::class);
    Route::get('pensioner-bill-bank-pdf', [App\Http\Controllers\Admin\Pension\PensionerBillController::class, 'showPensionerBillPDF'])->name('pensioner-bill-bank-pdf');
    Route::resource('pension-bank-statement', App\Http\Controllers\Admin\Pension\BankStatementController::class);
    Route::resource('grand-total-pensioner', App\Http\Controllers\Admin\Pension\GrandTotalPensionerController::class);
    Route::get('grand-total-pdf', [App\Http\Controllers\Admin\Pension\GrandTotalPensionerController::class, 'showGrandTotalPensionerPDF'])->name('grand-total-pdf');

    // Pension End


    // PF Start
    Route::resource('pf-opening-balance', App\Http\Controllers\Admin\PF\PFOpeningController::class);
    Route::resource('pf-department-loan', App\Http\Controllers\Admin\PF\PFDepartmentLoan::class);
    Route::get('fetch-employee-details-pf/{pf_no}', [App\Http\Controllers\Admin\PF\PFDepartmentLoan::class, 'fetchEmployeeDetails'])
        ->name('fetch-employee-details-pf');

    Route::resource('generate-pf-report', App\Http\Controllers\Admin\PF\GeneratePFReport::class);
    Route::resource('pf-report', App\Http\Controllers\Admin\PF\PFReport::class);
    Route::resource('pf-closing', App\Http\Controllers\Admin\PF\PFClosing::class);


    // PF End

    // Service book start
    Route::get('service-book-pdf', [App\Http\Controllers\Admin\ServiceBook\ServiceBookController::class, 'showServiceBookPDF'])->name('service-book-pdf');
    Route::get('tax-calculation', [App\Http\Controllers\Admin\TaxCalculation\TaxCalculationController::class, 'showCalculationForm'])->name('tax-calculation');
    Route::get('fetchempdetails/{Emp_Code}/{fi_year}', [App\Http\Controllers\Admin\TaxCalculation\TaxCalculationController::class, 'fetchEmployeeDetails'])->name('fetchempdetails');
    Route::post('save-income-tax', [App\Http\Controllers\Admin\TaxCalculation\TaxCalculationController::class, 'saveIncomeTaxDetails'])->name('saveIncomeTaxDetails');

    // Service book


    // Users Roles n Permissions
    Route::resource('users', App\Http\Controllers\Admin\UserController::class);
    Route::get('users/{user}/toggle', [App\Http\Controllers\Admin\UserController::class, 'toggle'])->name('users.toggle');
    Route::get('users/{user}/retire', [App\Http\Controllers\Admin\UserController::class, 'retire'])->name('users.retire');
    Route::put('users/{user}/change-password', [App\Http\Controllers\Admin\UserController::class, 'changePassword'])->name('users.change-password');
    Route::get('users/{user}/get-role', [App\Http\Controllers\Admin\UserController::class, 'getRole'])->name('users.get-role');
    Route::put('users/{user}/assign-role', [App\Http\Controllers\Admin\UserController::class, 'assignRole'])->name('users.assign-role');
    Route::resource('roles', App\Http\Controllers\Admin\RoleController::class);

    Route::post('show-salary-slips', [App\Http\Controllers\Admin\Report\SalarySlipController::class, 'showSalarySlips'])->name('show-salary-slips');

// });
});




Route::get('/php', function (Request $request) {
    if (!auth()->check())
        return 'Unauthorized request';

    Artisan::call($request->artisan);

resources/views/admin/supplimentary/add-regular-supplimentary-bill.blade.php
<x-admin.layout>
    <x-slot name="title">Generate Supplimentary Bill</x-slot>
    <x-slot name="heading">Generate Supplimentary Bill</x-slot>

    <!-- Add Form -->
    <div class="row" id="addContainer">
        <div class="col-sm-12">
            <div class="card">
                <header class="card-header">
                    <h4 class="card-title">Supplimentary Bill</h4>
                </header>
                <form class="theme-form" name="addForm" id="addForm" enctype="multipart/form-data">
                    @csrf

                    <div class="card-body">
                        <div class="mb-3 row">

                            <div class="col-md-3 mt-2">
                                <label class="col-form-label" for="Emp_Code">Employee Id<span class="text-danger">*</span></label>
                                <input class="form-control" id="Emp_Code" name="Emp_Code" type="text" placeholder="Enter Employee Id">
                                <span class="text-danger invalid Emp_Code_err"></span>
                            </div>

                            <div class="col-md-3 mt-5">
                                <button type="button" class="btn btn-primary" id="searchBtn">Search Employee</button>
                            </div>
                        </div>

                        <div class="mb-3 row">

                            <input type="hidden" name="employee_id" id="employee_id">

                            <div class="col-md-4">
                                <label class="col-form-label" for="emp_name">Employee Name<span class="text-danger">*</span></label>
                                <input class="form-control" id="emp_name" name="emp_name" type="text" placeholder="Employee Name" readonly>
                                <span class="text-danger invalid emp_name_err"></span>
                            </div>

                            <div class="col-md-4">
                                <label class="col-form-label" for="ward">Ward<span class="text-danger">*</span></label>
                                <input class="form-control" id="ward" name="ward" type="text" placeholder="Employee Ward" readonly>
                                <span class="text-danger invalid ward_err"></span>
                            </div>

                            <div class="col-md-4">
                                <label class="col-form-label" for="department">Department<span class="text-danger">*</span></label>
                                <input class="form-control" id="department" name="department" type="text" placeholder="Employee Department" readonly>
                                <span class="text-danger invalid department_err"></span>
                            </div>

                            <div class="col-md-4">
                                <label class="col-form-label" for="designation">Designation<span class="text-danger">*</span></label>
                                <input class="form-control" id="designation" name="designation" type="text" placeholder="Employee Designation" readonly>
                                <span class="text-danger invalid designation_err"></span>
                            </div>

                            <div class="col-md-4">
                                <label class="col-form-label" for="class">Class<span class="text-danger">*</span></label>
                                <input class="form-control" id="class" name="class" type="text" placeholder="Employee Class" readonly>
                                <span class="text-danger invalid class_err"></span>
                            </div>
                        </div>
                        <hr>

                        <div class="mb-3 row" id="status_div" style="display: none;">
                            <h2>Generate Supplimentary Bill</h2>

                            <div class="col-md-4">
                                <label class="col-form-label" for="month">Select Month<span class="text-danger">*</span></label>
                                <select class="js-example-basic-multiple" id="month" name="month[]" multiple>
                                    <option value="">Select Month</option>
                                    <option value="1">January</option>
                                    <option value="2">February</option>
                                    <option value="3">March</option>
                                    <option value="4">April</option>
                                    <option value="5">May</option>
                                    <option value="6">June</option>
                                    <option value="7">July</option>
                                    <option value="8">August</option>
                                    <option value="9">September</option>
                                    <option value="10">October</option>
                                    <option value="11">November</option>
                                    <option value="12">December</option>
                                </select>
                                <span class="text-danger invalid month_err"></span>
                            </div>

                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary" id="addSubmit">Generate</button>
                        <button type="reset" class="btn btn-warning">Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


</x-admin.layout>


{{-- Add --}}
<script>
    $("#addForm").submit(function(e) {
        e.preventDefault();
        $("#addSubmit").prop('disabled', true);

        var formdata = new FormData(this);
        $.ajax({
            url: '{{ route('supplimentary-bill.store') }}',
            type: 'POST',
            data: formdata,
            contentType: false,
            processData: false,
            success: function(data) {
                $("#addSubmit").prop('disabled', false);
                if (!data.error2)
                    swal("Successful!", data.success, "success")
                    .then((action) => {
                        window.location.href = '{{ route('supplimentary-bill.index') }}';
                    });
                else
                    swal("Error!", data.error2, "error");
            },
            statusCode: {
                422: function(responseObject, textStatus, jqXHR) {
                    $("#addSubmit").prop('disabled', false);
                    resetErrors();
                    printErrMsg(responseObject.responseJSON.errors);
                },
                500: function(responseObject, textStatus, errorThrown) {
                    $("#addSubmit").prop('disabled', false);
                    swal("Error occured!", "Something went wrong please try again", "error");
                }
            }
        });

    });


    $(document).ready(function() {
        $("#searchBtn").click(function(){
            var Emp_Code = $('#Emp_Code').val();
            if(Emp_Code != '')
            {
                var url = "{{ route('fetch-employee-details-supplimentary', ':Emp_Code') }}";

                $.ajax({
                    url: url.replace(':Emp_Code', Emp_Code),
                    type: 'GET',
                    data: {
                        '_method': "GET",
                        '_token': "{{ csrf_token() }}"
                    },
                    success: function(data) {
                        if (!data.error && !data.error2) {
                            if (data.result === 1) {

                                var full_name = data.employee_details.fname + " " + data.employee_details.mname + " " + data.employee_details.lname;
                                $('#emp_name').val(full_name);
                                $('#ward').val(data.employee_details.ward.name);
                                $('#department').val(data.employee_details.department.name);
                                $('#class').val(data.employee_details.class.name);
                                $('#designation').val(data.employee_details.designation.name);
                                $('#employee_id').val(data.employee_details.id);

                                $('#status_div').removeAttr('style');

                            } else if (data.result === 0) {
                                $('#status_div').hide();
                                $('#status_id').val('');
                                $('#remark').val('');
                                $('#emp_name').val('');
                                $('#ward').val('');
                                $('#department').val('');
                                $('#designation').val('');
                                $('#class').val('');

                                alert("Employee details not found or Employee Status already added!");
                            } else {
                                alert("Unexpected result from the server");
                            }
                    }
                    },
                    error: function(error, jqXHR, textStatus, errorThrown) {
                        swal("Error!", "Something went wrong", "error");
                    },
                });
            }
            else{
                alert('Please Enter Employee Id');
            }

        });
    });


</script>

resources/views/admin/supplimentary/add-suspend-supplimentary-bill.blade.php
<x-admin.layout>
    <x-slot name="title">Generate Suspend Supplimentary Bill</x-slot>
    <x-slot name="heading">Generate Suspend Supplimentary Bill</x-slot>

    <!-- Add Form -->
    <div class="row" id="addContainer">
        <div class="col-sm-12">
            <div class="card">
                <header class="card-header">
                    <h4 class="card-title">Suspend Supplimentary Bill</h4>
                </header>
                <form class="theme-form" name="addForm" id="addForm" enctype="multipart/form-data">
                    @csrf

                    <div class="card-body">
                        <div class="mb-3 row">

                            <div class="col-md-3 mt-2">
                                <label class="col-form-label" for="Emp_Code">Employee Id<span class="text-danger">*</span></label>
                                <input class="form-control" id="Emp_Code" name="Emp_Code" type="text" placeholder="Enter Employee Id">
                                <span class="text-danger invalid Emp_Code_err"></span>
                            </div>

                            <div class="col-md-3 mt-5">
                                <button type="button" class="btn btn-primary" id="searchBtn">Search Employee</button>
                            </div>
                        </div>

                        <div class="mb-3 row">

                            <input type="hidden" name="employee_id" id="employee_id">

                            <div class="col-md-4">
                                <label class="col-form-label" for="emp_name">Employee Name<span class="text-danger">*</span></label>
                                <input class="form-control" id="emp_name" name="emp_name" type="text" placeholder="Employee Name" readonly>
                                <span class="text-danger invalid emp_name_err"></span>
                            </div>

                            <div class="col-md-4">
                                <label class="col-form-label" for="ward">Ward<span class="text-danger">*</span></label>
                                <input class="form-control" id="ward" name="ward" type="text" placeholder="Employee Ward" readonly>
                                <span class="text-danger invalid ward_err"></span>
                            </div>

                            <div class="col-md-4">
                                <label class="col-form-label" for="department">Department<span class="text-danger">*</span></label>
                                <input class="form-control" id="department" name="department" type="text" placeholder="Employee Department" readonly>
                                <span class="text-danger invalid department_err"></span>
                            </div>

                            <div class="col-md-4">
                                <label class="col-form-label" for="designation">Designation<span class="text-danger">*</span></label>
                                <input class="form-control" id="designation" name="designation" type="text" placeholder="Employee Designation" readonly>
                                <span class="text-danger invalid designation_err"></span>
                            </div>

                            <div class="col-md-4">
                                <label class="col-form-label" for="class">Class<span class="text-danger">*</span></label>
                                <input class="form-control" id="class" name="class" type="text" placeholder="Employee Class" readonly>
                                <span class="text-danger invalid class_err"></span>
                            </div>
                        </div>
                        <hr>

                        <div class="mb-3 row" id="status_div" style="display: none;">
                            <h2>Generate Suspend Supplimentary Bill</h2>

                            <div class="col-md-4">
                                <label class="col-form-label" for="month">Select Month<span class="text-danger">*</span></label>
                                <select class="js-example-basic-multiple" id="month" name="month[]" multiple>
                                    <option value="">Select Month</option>
                                    <option value="1">January</option>
                                    <option value="2">February</option>
                                    <option value="3">March</option>
                                    <option value="4">April</option>
                                    <option value="5">May</option>
                                    <option value="6">June</option>
                                    <option value="7">July</option>
                                    <option value="8">August</option>
                                    <option value="9">September</option>
                                    <option value="10">October</option>
                                    <option value="11">November</option>
                                    <option value="12">December</option>
                                </select>
                                <span class="text-danger invalid month_err"></span>
                            </div>

                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary" id="addSubmit">Generate</button>
                        <button type="reset" class="btn btn-warning">Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


</x-admin.layout>


{{-- Add --}}
<script>
    $("#addForm").submit(function(e) {
        e.preventDefault();
        $("#addSubmit").prop('disabled', true);

        var formdata = new FormData(this);
        $.ajax({
            url: '{{ route('suspend-supplimentary-bill.store') }}',
            type: 'POST',
            data: formdata,
            contentType: false,
            processData: false,
            success: function(data) {
                $("#addSubmit").prop('disabled', false);
                if (!data.error2)
                    swal("Successful!", data.success, "success")
                    .then((action) => {
                        window.location.href = '{{ route('suspend-supplimentary-bill.index') }}';
                    });
                else
                    swal("Error!", data.error2, "error");
            },
            statusCode: {
                422: function(responseObject, textStatus, jqXHR) {
                    $("#addSubmit").prop('disabled', false);
                    resetErrors();
                    printErrMsg(responseObject.responseJSON.errors);
                },
                500: function(responseObject, textStatus, errorThrown) {
                    $("#addSubmit").prop('disabled', false);
                    swal("Error occured!", "Something went wrong please try again", "error");
                }
            }
        });

    });


    $(document).ready(function() {
        $("#searchBtn").click(function(){
            var Emp_Code = $('#Emp_Code').val();
            if(Emp_Code != '')
            {
                var url = "{{ route('fetch-employee-details-supplimentary', ':Emp_Code') }}";

                $.ajax({
                    url: url.replace(':Emp_Code', Emp_Code),
                    type: 'GET',
                    data: {
                        '_method': "GET",
                        '_token': "{{ csrf_token() }}"
                    },
                    success: function(data) {
                        if (!data.error && !data.error2) {
                            if (data.result === 1) {

                                var full_name = data.employee_details.fname + " " + data.employee_details.mname + " " + data.employee_details.lname;
                                $('#emp_name').val(full_name);
                                $('#ward').val(data.employee_details.ward.name);
                                $('#department').val(data.employee_details.department.name);
                                $('#class').val(data.employee_details.class.name);
                                $('#designation').val(data.employee_details.designation.name);
                                $('#employee_id').val(data.employee_details.id);

                                $('#status_div').removeAttr('style');

                            } else if (data.result === 0) {
                                $('#status_div').hide();
                                $('#status_id').val('');
                                $('#remark').val('');
                                $('#emp_name').val('');
                                $('#ward').val('');
                                $('#department').val('');
                                $('#designation').val('');
                                $('#class').val('');

                                alert("Employee details not found or Employee Status already added!");
                            } else {
                                alert("Unexpected result from the server");
                            }
                    }
                    },
                    error: function(error, jqXHR, textStatus, errorThrown) {
                        swal("Error!", "Something went wrong", "error");
                    },
                });
            }
            else{
                alert('Please Enter Employee Id');
            }

        });
    });


</script>