routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
})->name('/');




// Guest Users
Route::middleware(['guest', 'PreventBackHistory'])->group(function () {
    Route::get('login', [App\Http\Controllers\Admin\AuthController::class, 'showLogin'])->name('login');
    Route::post('login', [App\Http\Controllers\Admin\AuthController::class, 'login'])->name('signin');
    Route::get('register', [App\Http\Controllers\Admin\AuthController::class, 'showRegister'])->name('register');
    Route::post('register', [App\Http\Controllers\Admin\AuthController::class, 'register'])->name('signup');
});


Route::resource('salary-slips', App\Http\Controllers\Admin\Report\SalarySlipController::class);
Route::resource('yearly-pay-sheet', App\Http\Controllers\Admin\Report\YearlyPaySheetController::class);
Route::get('yearly-pay-sheet-pdf/{emp_id?}/{finyear?}', [App\Http\Controllers\Admin\Report\YearlyPaySheetController::class, 'showPaySheetPDF'])->name('yearly-pay-sheet-pdf');

// Authenticated users
Route::middleware(['auth', 'PreventBackHistory'])->group(function () {

    // Auth Routes
    Route::get('home', fn () => redirect()->route('dashboard'))->name('home');
    // Route::middleware('role:Employee,true')->group(function () {
    Route::get('dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');
    Route::post('logout', [App\Http\Controllers\Admin\AuthController::class, 'Logout'])->name('logout');
    Route::get('change-theme-mode', [App\Http\Controllers\Admin\DashboardController::class, 'changeThemeMode'])->name('change-theme-mode');
    Route::get('show-change-password', [App\Http\Controllers\Admin\AuthController::class, 'showChangePassword'])->name('show-change-password');
    Route::post('change-password', [App\Http\Controllers\Admin\AuthController::class, 'changePassword'])->name('change-password');



    // Masters
    Route::resource('wards', App\Http\Controllers\Admin\Masters\WardController::class);
    Route::resource('department', App\Http\Controllers\Admin\Masters\DepartmentController::class);
    Route::resource('class', App\Http\Controllers\Admin\Masters\ClassController::class);
    Route::resource('bank', App\Http\Controllers\Admin\Masters\BankController::class);
    Route::resource('financial_year', App\Http\Controllers\Admin\Masters\FinancialYearController::class);
    Route::resource('allowance', App\Http\Controllers\Admin\Masters\AllowanceController::class);
    Route::resource('deduction', App\Http\Controllers\Admin\Masters\DeductionController::class);
    Route::resource('loan', App\Http\Controllers\Admin\Masters\LoanController::class);
    // To Change Activity Status of Loan
    Route::post('loan-activity-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Masters\LoanController::class, 'changeStatus'])->name('loan-activity-status');

    Route::resource('designation', App\Http\Controllers\Admin\Masters\DesignationController::class);
    // Fetch departments on ward
    Route::get('fetch-departments/{ward_id}', [App\Http\Controllers\Admin\Masters\DesignationController::class, 'fetchDepartment'])->name('fetch-departments');

    Route::resource('leave-type', App\Http\Controllers\Admin\Masters\LeaveTypeController::class);
    Route::resource('pay-scale', App\Http\Controllers\Admin\Masters\PayScaleController::class);
    Route::resource('status', App\Http\Controllers\Admin\Masters\StatusController::class);
    Route::resource('pension-bank', App\Http\Controllers\Admin\Masters\PensionBankController::class);
    Route::resource('intrest-rate', App\Http\Controllers\Admin\Masters\IntrestRateController::class);
    // To Change Activity Status of Loan
    Route::post('intrest-rate-activity-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Masters\IntrestRateController::class, 'changeStatus'])->name('intrest-rate-activity-status');

    Route::resource('document', App\Http\Controllers\Admin\Masters\DocumentController::class);
    Route::resource('working-department', App\Http\Controllers\Admin\Masters\WorkingDepartmentController::class);
    Route::resource('castes', App\Http\Controllers\Admin\Masters\CasteController::class);



    //Employee List
    Route::get('employee-basic-form', [App\Http\Controllers\Admin\Employee\EmployeeController::class, 'employeeBasicUpdateForm'])->name('employee-basic-form');
    Route::put('employee-basic-update/{id}', [App\Http\Controllers\Admin\Employee\EmployeeController::class, 'employeeBasicUpdate'])->name('employee-basic-update');

    Route::resource('employee', App\Http\Controllers\Admin\Employee\EmployeeController::class);
    Route::post('employee-activity-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Employee\EmployeeController::class, 'changeStatus'])->name('employee-activity-status');


    Route::resource('employee-transfer', App\Http\Controllers\Admin\Employee\EmployeeTransferController::class);

    // Fetch Class
    Route::get('fetch-class/{employee_category}', [App\Http\Controllers\Admin\Masters\ClassController::class, 'fetchClass'])->name('fetch-class');

    // Fetch designation on ward/class/department
    Route::get('fetch-designations/{ward_id}/{department_id}/{class_id}', [App\Http\Controllers\Admin\Employee\EmployeeController::class, 'fetchDesignation'])->name('fetch-designations');
    Route::get('fetch-working-years/{class_id}/{dob}', [App\Http\Controllers\Admin\Employee\EmployeeController::class, 'fetchWorkingYear'])->name('fetch-working-years');

    Route::resource('employee-status', App\Http\Controllers\Admin\Employee\EmployeeStatusController::class);
    Route::get('fetch-employee-details/{Emp_Code}', [App\Http\Controllers\Admin\Employee\EmployeeStatusController::class, 'fetchEmployeeDetails'])
        ->name('fetch-employee-details');


    // Salary Structure
    Route::resource('employee-salary', App\Http\Controllers\Admin\Employee\EmployeeSalaryController::class);
    Route::get('fetch-payscale-details/{pay_scale_id}', [App\Http\Controllers\Admin\Employee\EmployeeSalaryController::class, 'fetchpayScaleDetails'])
        ->name('fetch-payscale-details');

    Route::resource('basic-salary-increment', App\Http\Controllers\Admin\Employee\BasicSalaryIncrementController::class);
    Route::get('get-incremented-salary', [App\Http\Controllers\Admin\Employee\BasicSalaryIncrementController::class, 'getIncrementedBasicSalary'])
        ->name('get-incremented-salary');

    Route::resource('allowance-increment', App\Http\Controllers\Admin\Employee\AllowanceIncrementController::class);
    Route::get('fetch-allowance-details/{allowance_id}', [App\Http\Controllers\Admin\Employee\AllowanceIncrementController::class, 'fetchAllowanceDetails'])
        ->name('fetch-allowance-details');
    Route::get('get-incremented-allowance', [App\Http\Controllers\Admin\Employee\AllowanceIncrementController::class, 'getIncrementedAllowance'])
        ->name('get-incremented-allowance');

    Route::resource('deduction-increment', App\Http\Controllers\Admin\Employee\DeductionIncrementController::class);
    Route::get('fetch-deduction-details/{deduction_id}', [App\Http\Controllers\Admin\Employee\DeductionIncrementController::class, 'fetchDeductionDetails'])
        ->name('fetch-deduction-details');
    Route::get('get-incremented-deduction', [App\Http\Controllers\Admin\Employee\DeductionIncrementController::class, 'getIncrementedDeduction'])
        ->name('get-incremented-deduction');

    // DA Differance
    Route::resource('da-differance', App\Http\Controllers\Admin\Employee\DADifferanceController::class);
    Route::get('fetch-current-da', [App\Http\Controllers\Admin\Employee\DADifferanceController::class, 'fetchCurrentDA'])->name('fetch-current-da');



    // End Salary Structure


    // Employee Loans / LIC /Festival Advance Start
    Route::resource('employee-loans', App\Http\Controllers\Admin\Employee\EmployeeLoanController::class);
    Route::post('employee-loan-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Employee\EmployeeLoanController::class, 'employeeLoanStatus'])->name('employee-loan-status');

    Route::resource('employee-monthly-loans', App\Http\Controllers\Admin\Employee\EmployeeMonthlyLoanController::class);
    Route::get('employee-monthly-loans/{from_date}/{to_date}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyLoanController::class, 'showEmployeeLoans'])->name('employee-monthly-loans.showEmployeeLoans');
    Route::post('employee-monthly-loan-status/{model_id}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyLoanController::class, 'employeeMonthlyLoanStatus'])->name('employee-monthly-loan-status');

    Route::resource('yearly-bonus', App\Http\Controllers\Admin\Employee\YearlyBonusController::class);
    Route::get('fetch-emp-details/{Emp_Code}', [App\Http\Controllers\Admin\Employee\YearlyBonusController::class, 'fetchEmployeeDetails'])->name('fetch-emp-details');
    
    // LIC
    Route::resource('lic-dedcution', App\Http\Controllers\Admin\Employee\LICDeductionController::class);
    Route::post('employee-lic-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Employee\LICDeductionController::class, 'employeeLicStatus'])->name('employee-lic-status');

    Route::resource('employee-monthly-lic', App\Http\Controllers\Admin\Employee\EmployeeMonthlyLicController::class);

app/Http/Controllers/Admin/Employee/AllowanceIncrementController.php
<?php

namespace App\Http\Controllers\Admin\Employee;

use App\Http\Controllers\Admin\Controller;
use App\Http\Requests\Admin\Employee\StoreIncrementAllowanceRequest;
use App\Models\Allowance;
use App\Models\Department;
use Illuminate\Http\Request;
use App\Models\Clas;
use App\Models\Employee;
use App\Models\EmployeeAllowance;
use App\Models\IncrementAllowanceSalary;
use App\Models\OldEmployeeAllowance;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class AllowanceIncrementController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $authUser = Auth::user();

        $departments = Department::
                            when($authUser->hasRole(['Ward HOD']), function ($query) use ($authUser) {
                                return $query->where('ward_id', $authUser->ward_id);
                            })
                            ->when($authUser->id == 1, function ($query) {
                                return $query->where('ward_id','!=', 84);
                            })
                            ->latest()->get();
        $allowances = Allowance::latest()->get();;
        $classes = Clas::latest()->get();

        return view('admin.employee.allowance-increment')->with(['departments' => $departments, 'allowances' => $allowances, 'classes' => $classes]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreIncrementAllowanceRequest $request)
    {
        $authUser = Auth::user();

        try {
            DB::beginTransaction();
            $input = $request->validated();

            if ($input['department_id'] == 'all') {
                $input['department_id'] = 0;
            } else {
                $input['department_id'] = $input['department_id'];
            }

            if ($input['clas_id'] == 'all') {
                $input['clas_id'] = 0;
            } else {
                $input['clas_id'] = $input['clas_id'];
            }

            IncrementAllowanceSalary::create(Arr::only($input, IncrementAllowanceSalary::getFillables()));
            $emp_ids = $input['emp_id'];
            $allowance = $input['allowance_id'];

            $allowance_unique_id = $input['allowance_unique_id'];
            foreach ($emp_ids as $key => $emp_id) {

                $employee_allowance = EmployeeAllowance::where('employee_id', $emp_id)->where('id', $allowance_unique_id[$key]);

                $old_employee_allowance = OldEmployeeAllowance::where('employee_id', $emp_id)->where('allowance_id', $allowance)->latest()->first();

                $employee_allowance->update([
                    'allowance_amt' => $input['new_amount'],
                    'updated_by' => $authUser->id,
                    'updated_at' => now(),
                ]);

                $old_employee_allowance->update([
                    'end_date' => date('Y-m-d'),
                    'updated_by' => $authUser->id,
                    'updated_at' => now(),
                    'is_active' => 0,
                ]);

                $old_employee_salary_create = [
                    'employee_id' => $emp_id,
                    'Emp_Code' => $old_employee_allowance->Emp_Code,
                    'old_employee_salary_id' => $old_employee_allowance->old_employee_salary_id,
                    'allowance_id' => $allowance,
                    'allowance_amt' => $input['new_amount'],
                    'allowance_type' => $old_employee_allowance->allowance_type,
                    'is_active' => 1,
                    'applicable_date' => date('Y-m-d')
                ];

                OldEmployeeAllowance::create($old_employee_salary_create);
            }

            DB::commit();

            return response()->json(['success' => 'Basic Salary Increment successfully!']);
        } catch (\Exception $e) {
            return $this->respondWithAjax($e, 'creating', 'Basic Salary');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }

    public function fetchAllowanceDetails($allowance_id)
    {
        $allowanceDetails = Allowance::where('id', $allowance_id)->get()->first();

        if ($allowanceDetails) {
            $response = [
                'result' => 1,
                'allowanceDetails' => $allowanceDetails,
            ];
        } else {
            $response = ['result' => 0];
        }
        return $response;
    }

    public function getIncrementedAllowance(Request $request)
    {
        try {
            $departmentId = $request->input('department_id');
            $clas_id = $request->input('clas_id');
            $allowance_id = $request->input('allowance_id');
            $new_amount = $request->input('new_amount');

            $get_employees = Employee::with('department')->when(
                $departmentId == 'all',
                function ($query) {
                    return $query->latest();
                },
                function ($query) use ($departmentId, $clas_id) {
                    $query->when($departmentId != 'all', function ($subquery) use ($departmentId) {
                        $subquery->where('department_id', $departmentId);
                    })->when($clas_id != 'all', function ($subquery) use ($clas_id) {
                        $subquery->where('clas_id', $clas_id);
                    });

                    return $query->latest();
                }
            )->get();

            $incrementArr = [];

            foreach ($get_employees as $key => $employee) {

                $employeeSalary = EmployeeAllowance::with('allowance')->where('employee_id', $employee->id)
                    ->where('allowance_id', $allowance_id)->first();

                if ($employeeSalary) {
                    $incrementArr[] = [
                        'sr_no'                 =>  $key + 1,
                        'employee_uniques_id'   =>  $employee->id,
                        'allowance_unique_id'   =>  $employeeSalary->id,
                        'emp_id'                =>  $employee->employee_id,
                        'emp_name'              =>  $employee->fname . " " . $employee->mname . " " . $employee->lname,
                        'department'            =>  $employee->department->name,
                        'allowance'             =>  $employeeSalary->allowance->allowance,
                        'current_allowances'    =>  $employeeSalary->allowance_amt,
                        'increment_allowances'  =>  $new_amount,
                    ];
                }
            }

            $response = [
                'result' => 1,
                'incrementArr' => $incrementArr,
            ];

            return response()->json($response);
        } catch (\Exception $e) {
            return response()->json(['result' => 0, 'error' => $e->getMessage()]);
        }
    }
}

resources/views/admin/employee/da-differance-list.blade.php
<x-admin.layout>
    <x-slot name="title">DA Differance Employee List</x-slot>
    <x-slot name="heading">DA Differance Employee List</x-slot>


    <div class="row">
        <div class="col-lg-12">
            <div class="card">

                <div class="card-body">
                    <div class="table-responsive">
                        <table id="buttons-datatables" class="table table-bordered nowrap align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Sr No.</th>
                                    <th>Employee Id</th>
                                    <th>Name</th>
                                    <th>Current DA Rate</th>
                                    <th>New DA Rate</th>
                                    <th>Applicable Month</th>
                                    <th>Applied Month</th>
                                    <th>No. of Months</th>
                                    <th>Differance</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach ($employee_da_differances as $daDifferance)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $daDifferance->Emp_Code }}</td>
                                        <td>{{ $daDifferance->employee->fname." ".$daDifferance->employee->mname." ".$daDifferance->employee->lname }}</td>
                                        <td>{{ $daDifferance->DA_currentRate }}</td>
                                        <td>{{ $daDifferance->DA_newRate }}</td>
                                        <td>{{ $daDifferance->applicable_month }}</td>
                                        <td>{{ $daDifferance->given_month }}</td>
                                        <td>{{ $daDifferance->no_of_month }}</td>
                                        <td>{{ $daDifferance->differance }}</td>
                                        <td>{{ ($daDifferance->status == 0)?'Pending':'Applied'; }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




</x-admin.layout>

resources/views/admin/employee/da-differance.blade.php
<x-admin.layout>
    <x-slot name="title">DA Differance</x-slot>
    <x-slot name="heading">DA Differance</x-slot>

    <!-- Add Form -->
    <div class="row" id="addContainer" style="display:none;">
        <div class="col-sm-12">
            <div class="card">
                <header class="card-header">
                    <h4 class="card-title">Add DA Differance</h4>
                </header>
                <form class="theme-form" name="addForm" id="addForm" enctype="multipart/form-data">
                    @csrf

                    <div class="card-body">
                        <div class="mb-3 row">
                            <div class="col-md-4">
                                <label class="col-form-label" for="DA_currentRate">DA Current Rate<span class="text-danger">*</span></label>
                                <input class="form-control title" id="DA_currentRate" name="DA_currentRate" type="text" placeholder="Enter DA Current Rate">
                                <span class="text-danger invalid DA_currentRate_err"></span>
                            </div>
                            <div class="col-md-4">
                                <label class="col-form-label" for="DA_newRate">DA New Rate<span class="text-danger">*</span></label>
                                <input class="form-control title" id="DA_newRate" name="DA_newRate" type="text" placeholder="Enter DA New Rate">
                                <span class="text-danger invalid DA_newRate_err"></span>
                            </div>

                            <div class="col-md-4">
                                <label class="col-form-label" for="applicable_month">Applicable Month<span class="text-danger">*</span></label>
                                <select class="form-control" id="applicable_month" name="applicable_month">
                                    <option value="">Select Applicable Month</option>
                                    <option value="1" {{ (old('applicable_month') == 1)?'Selected':'' }} >January</option>
                                    <option value="2" {{ (old('applicable_month') == 2)?'Selected':'' }}>February</option>
                                    <option value="3" {{ (old('applicable_month') == 3)?'Selected':'' }}>March</option>
                                    <option value="4" {{ (old('applicable_month') == 4)?'Selected':'' }}>April</option>
                                    <option value="5" {{ (old('applicable_month') == 5)?'Selected':'' }}>May</option>
                                    <option value="6" {{ (old('applicable_month') == 6)?'Selected':'' }}>June</option>
                                    <option value="7" {{ (old('applicable_month') == 7)?'Selected':'' }}>July</option>
                                    <option value="8" {{ (old('applicable_month') == 8)?'Selected':'' }}>August</option>
                                    <option value="9" {{ (old('applicable_month') == 9)?'Selected':'' }}>September</option>
                                    <option value="10" {{ (old('applicable_month') == 10)?'Selected':'' }}>October</option>
                                    <option value="11" {{ (old('applicable_month') == 11)?'Selected':'' }}>November</option>
                                    <option value="12" {{ (old('applicable_month') == 12)?'Selected':'' }}>December</option>
                                </select>
                                <span class="text-danger invalid applicable_month_err"></span>
                            </div>

                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary" id="addSubmit">Submit</button>
                        <button type="reset" class="btn btn-warning">Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                {{-- @can('allowance.create') --}}
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="">
                                    <button id="addToTable" class="btn btn-primary">Add <i class="fa fa-plus"></i></button>
                                    <button id="btnCancel" class="btn btn-danger" style="display:none;">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                {{-- @endcan --}}
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="buttons-datatables" class="table table-bordered nowrap align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Sr No.</th>
                                    <th>Current DA Rate</th>
                                    <th>New DA Rate</th>
                                    <th>Applicable Month</th>
                                    <th>Applied Month</th>
                                    <th>No. of Months</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($daDifferances as $daDifferance)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $daDifferance->DA_currentRate }}</td>
                                        <td>{{ $daDifferance->DA_newRate }}</td>
                                        <td>{{ $daDifferance->applicable_month }}</td>
                                        <td>{{ $daDifferance->given_month }}</td>
                                        <td>{{ $daDifferance->no_of_month }}</td>
                                        <td>
                                            <a href="{{ route('da-differance.show',$daDifferance->id) }}" class="edit-element btn btn-secondary px-2 py-1" title="Show Employee">
                                                <i data-feather="eye"></i>
                                            </a>

                                            {{-- @can('allowance.delete')  --}}
                                                {{-- <button class="btn btn-danger rem-element px-2 py-1" title="Delete DA Differance" data-id="{{ $daDifferance->id }}"><i data-feather="trash-2"></i> </button> --}}
                                            {{-- @endcan --}}


                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




</x-admin.layout>


{{-- Add --}}
<script>

    $(document).ready(function() {

        var url = "{{ route('fetch-current-da') }}";
        $.ajax({
            url: url,
            type: "GET",
            data: {
                _method: "GET",
                _token: "{{ csrf_token() }}",
            },
            success: function (data, textStatus, jqXHR) {
                if (!data.error) {
                    $("#DA_currentRate").val(data.allowance_arr.amount);
                } else {
                    alert(data.error);
                }
            },
            error: function (error, jqXHR, textStatus, errorThrown) {
                swal("Error!", "Something went wrong", "error");
            },
        });
    });

    $("#DA_newRate").on("change", function (e) {

        var DA_currentRate  = $('#DA_currentRate').val();
        var DA_newRate      = $("#DA_newRate").val();
        if(parseInt(DA_newRate) < parseInt(DA_currentRate)){

            alert('DA New Rate Should be greater than current rate');
            $("#DA_newRate").val('');
        }

    });

    $("#addForm").submit(function(e) {
        e.preventDefault();
        $("#addSubmit").prop('disabled', true);
        var formdata = new FormData(this);
        $.ajax({
            url: '{{ route('da-differance.store') }}',
            type: 'POST',
            data: formdata,
            contentType: false,
            processData: false,
            success: function(data) {
                $("#addSubmit").prop('disabled', false);
                if (!data.error2)
                    swal("Successful!", data.success, "success")
                    .then((action) => {
                        window.location.href = '{{ route('da-differance.index') }}';
                    });
                else
                    swal("Error!", data.error2, "error");
            },
            statusCode: {
                422: function(responseObject, textStatus, jqXHR) {
                    $("#addSubmit").prop('disabled', false);
                    resetErrors();
                    printErrMsg(responseObject.responseJSON.errors);
                },
                500: function(responseObject, textStatus, errorThrown) {
                    $("#addSubmit").prop('disabled', false);
                    swal("Error occured!", "Something went wrong please try again", "error");
                }
            }
        });

    });
</script>


<!-- Delete -->
<script>
    $("#buttons-datatables").on("click", ".rem-element", function(e) {
        e.preventDefault();
        swal({
                title: "Are you sure to delete this DA Differance?",
                icon: "info",
                buttons: ["Cancel", "Confirm"]
            })
            .then((justTransfer) => {
                if (justTransfer) {
                    var model_id = $(this).attr("data-id");
                    var url = "{{ route('da-differance.destroy', ':model_id') }}";

                    $.ajax({
                        url: url.replace(':model_id', model_id),
                        type: 'POST',
                        data: {
                            '_method': "DELETE",
                            '_token': "{{ csrf_token() }}"
                        },
                        success: function(data, textStatus, jqXHR) {
                            if (!data.error && !data.error2) {
                                swal("Success!", data.success, "success")
                                    .then((action) => {
                                        window.location.reload();
                                    });
                            } else {
                                if (data.error) {
                                    swal("Error!", data.error, "error");
                                } else {
                                    swal("Error!", data.error2, "error");
                                }
                            }
                        },
                        error: function(error, jqXHR, textStatus, errorThrown) {
                            swal("Error!", "Something went wrong", "error");
                        },
                    });
                }
            });
    });
</script>