routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
})->name('/');




// Guest Users
Route::middleware(['guest', 'PreventBackHistory'])->group(function () {
    Route::get('login', [App\Http\Controllers\Admin\AuthController::class, 'showLogin'])->name('login');
    Route::post('login', [App\Http\Controllers\Admin\AuthController::class, 'login'])->name('signin');
    Route::get('register', [App\Http\Controllers\Admin\AuthController::class, 'showRegister'])->name('register');
    Route::post('register', [App\Http\Controllers\Admin\AuthController::class, 'register'])->name('signup');
});


Route::resource('salary-slips', App\Http\Controllers\Admin\Report\SalarySlipController::class);
Route::resource('yearly-pay-sheet', App\Http\Controllers\Admin\Report\YearlyPaySheetController::class);
Route::get('yearly-pay-sheet-pdf/{emp_id?}/{finyear?}', [App\Http\Controllers\Admin\Report\YearlyPaySheetController::class, 'showPaySheetPDF'])->name('yearly-pay-sheet-pdf');

// Authenticated users
Route::middleware(['auth', 'PreventBackHistory'])->group(function () {

    // Auth Routes
    Route::get('home', fn () => redirect()->route('dashboard'))->name('home');
    // Route::middleware('role:Employee,true')->group(function () {
    Route::get('dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');
    Route::post('logout', [App\Http\Controllers\Admin\AuthController::class, 'Logout'])->name('logout');
    Route::get('change-theme-mode', [App\Http\Controllers\Admin\DashboardController::class, 'changeThemeMode'])->name('change-theme-mode');
    Route::get('show-change-password', [App\Http\Controllers\Admin\AuthController::class, 'showChangePassword'])->name('show-change-password');
    Route::post('change-password', [App\Http\Controllers\Admin\AuthController::class, 'changePassword'])->name('change-password');



    // Masters
    Route::resource('wards', App\Http\Controllers\Admin\Masters\WardController::class);
    Route::resource('department', App\Http\Controllers\Admin\Masters\DepartmentController::class);
    Route::resource('class', App\Http\Controllers\Admin\Masters\ClassController::class);
    Route::resource('bank', App\Http\Controllers\Admin\Masters\BankController::class);
    Route::resource('financial_year', App\Http\Controllers\Admin\Masters\FinancialYearController::class);
    Route::resource('allowance', App\Http\Controllers\Admin\Masters\AllowanceController::class);
    Route::resource('deduction', App\Http\Controllers\Admin\Masters\DeductionController::class);
    Route::resource('loan', App\Http\Controllers\Admin\Masters\LoanController::class);
    // To Change Activity Status of Loan
    Route::post('loan-activity-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Masters\LoanController::class, 'changeStatus'])->name('loan-activity-status');

    Route::resource('designation', App\Http\Controllers\Admin\Masters\DesignationController::class);
    // Fetch departments on ward
    Route::get('fetch-departments/{ward_id}', [App\Http\Controllers\Admin\Masters\DesignationController::class, 'fetchDepartment'])->name('fetch-departments');

    Route::resource('leave-type', App\Http\Controllers\Admin\Masters\LeaveTypeController::class);
    Route::resource('pay-scale', App\Http\Controllers\Admin\Masters\PayScaleController::class);
    Route::resource('status', App\Http\Controllers\Admin\Masters\StatusController::class);
    Route::resource('pension-bank', App\Http\Controllers\Admin\Masters\PensionBankController::class);
    Route::resource('intrest-rate', App\Http\Controllers\Admin\Masters\IntrestRateController::class);
    // To Change Activity Status of Loan
    Route::post('intrest-rate-activity-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Masters\IntrestRateController::class, 'changeStatus'])->name('intrest-rate-activity-status');

    Route::resource('document', App\Http\Controllers\Admin\Masters\DocumentController::class);
    Route::resource('working-department', App\Http\Controllers\Admin\Masters\WorkingDepartmentController::class);
    Route::resource('castes', App\Http\Controllers\Admin\Masters\CasteController::class);



    //Employee List
    Route::get('employee-basic-form', [App\Http\Controllers\Admin\Employee\EmployeeController::class, 'employeeBasicUpdateForm'])->name('employee-basic-form');
    Route::put('employee-basic-update/{id}', [App\Http\Controllers\Admin\Employee\EmployeeController::class, 'employeeBasicUpdate'])->name('employee-basic-update');

    Route::resource('employee', App\Http\Controllers\Admin\Employee\EmployeeController::class);
    Route::post('employee-activity-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Employee\EmployeeController::class, 'changeStatus'])->name('employee-activity-status');


    Route::resource('employee-transfer', App\Http\Controllers\Admin\Employee\EmployeeTransferController::class);

    // Fetch Class
    Route::get('fetch-class/{employee_category}', [App\Http\Controllers\Admin\Masters\ClassController::class, 'fetchClass'])->name('fetch-class');

    // Fetch designation on ward/class/department
    Route::get('fetch-designations/{ward_id}/{department_id}/{class_id}', [App\Http\Controllers\Admin\Employee\EmployeeController::class, 'fetchDesignation'])->name('fetch-designations');
    Route::get('fetch-working-years/{class_id}/{dob}', [App\Http\Controllers\Admin\Employee\EmployeeController::class, 'fetchWorkingYear'])->name('fetch-working-years');

    Route::resource('employee-status', App\Http\Controllers\Admin\Employee\EmployeeStatusController::class);
    Route::get('fetch-employee-details/{Emp_Code}', [App\Http\Controllers\Admin\Employee\EmployeeStatusController::class, 'fetchEmployeeDetails'])
        ->name('fetch-employee-details');


    // Salary Structure
    Route::resource('employee-salary', App\Http\Controllers\Admin\Employee\EmployeeSalaryController::class);
    Route::get('fetch-payscale-details/{pay_scale_id}', [App\Http\Controllers\Admin\Employee\EmployeeSalaryController::class, 'fetchpayScaleDetails'])
        ->name('fetch-payscale-details');

    Route::resource('basic-salary-increment', App\Http\Controllers\Admin\Employee\BasicSalaryIncrementController::class);
    Route::get('get-incremented-salary', [App\Http\Controllers\Admin\Employee\BasicSalaryIncrementController::class, 'getIncrementedBasicSalary'])
        ->name('get-incremented-salary');

    Route::resource('allowance-increment', App\Http\Controllers\Admin\Employee\AllowanceIncrementController::class);
    Route::get('fetch-allowance-details/{allowance_id}', [App\Http\Controllers\Admin\Employee\AllowanceIncrementController::class, 'fetchAllowanceDetails'])
        ->name('fetch-allowance-details');
    Route::get('get-incremented-allowance', [App\Http\Controllers\Admin\Employee\AllowanceIncrementController::class, 'getIncrementedAllowance'])
        ->name('get-incremented-allowance');

    Route::resource('deduction-increment', App\Http\Controllers\Admin\Employee\DeductionIncrementController::class);
    Route::get('fetch-deduction-details/{deduction_id}', [App\Http\Controllers\Admin\Employee\DeductionIncrementController::class, 'fetchDeductionDetails'])
        ->name('fetch-deduction-details');
    Route::get('get-incremented-deduction', [App\Http\Controllers\Admin\Employee\DeductionIncrementController::class, 'getIncrementedDeduction'])
        ->name('get-incremented-deduction');

    // DA Differance
    Route::resource('da-differance', App\Http\Controllers\Admin\Employee\DADifferanceController::class);
    Route::get('fetch-current-da', [App\Http\Controllers\Admin\Employee\DADifferanceController::class, 'fetchCurrentDA'])->name('fetch-current-da');



    // End Salary Structure


    // Employee Loans / LIC /Festival Advance Start
    Route::resource('employee-loans', App\Http\Controllers\Admin\Employee\EmployeeLoanController::class);
    Route::post('employee-loan-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Employee\EmployeeLoanController::class, 'employeeLoanStatus'])->name('employee-loan-status');

    Route::resource('employee-monthly-loans', App\Http\Controllers\Admin\Employee\EmployeeMonthlyLoanController::class);
    Route::get('employee-monthly-loans/{from_date}/{to_date}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyLoanController::class, 'showEmployeeLoans'])->name('employee-monthly-loans.showEmployeeLoans');
    Route::post('employee-monthly-loan-status/{model_id}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyLoanController::class, 'employeeMonthlyLoanStatus'])->name('employee-monthly-loan-status');

    Route::resource('yearly-bonus', App\Http\Controllers\Admin\Employee\YearlyBonusController::class);
    Route::get('fetch-emp-details/{Emp_Code}', [App\Http\Controllers\Admin\Employee\YearlyBonusController::class, 'fetchEmployeeDetails'])->name('fetch-emp-details');
    
    // LIC
    Route::resource('lic-dedcution', App\Http\Controllers\Admin\Employee\LICDeductionController::class);
    Route::post('employee-lic-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Employee\LICDeductionController::class, 'employeeLicStatus'])->name('employee-lic-status');

    Route::resource('employee-monthly-lic', App\Http\Controllers\Admin\Employee\EmployeeMonthlyLicController::class);

app/Http/Controllers/Admin/Masters/AllowanceController.php
<?php

namespace App\Http\Controllers\Admin\Masters;

use App\Http\Controllers\Admin\Controller;
use Illuminate\Http\Request;
use App\Models\Allowance;
use App\Http\Requests\Admin\Masters\StoreAllowanceRequest;
use App\Http\Requests\Admin\Masters\UpdateAllowanceRequest;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;

class AllowanceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $allowance = Allowance::latest()->get();

        return view('admin.masters.allowance')->with(['allowances' => $allowance]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreAllowanceRequest $request)
    {
        try {
            DB::beginTransaction();
            $input = $request->validated();
            Allowance::create(Arr::only($input, Allowance::getFillables()));
            DB::commit();

            return response()->json(['success' => 'Allowance created successfully!']);
        } catch (\Exception $e) {
            return $this->respondWithAjax($e, 'creating', 'Allowance');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Allowance $allowance)
    {
        if ($allowance) {

            $typeHtml = '<span>
            <option value="">--Select Type--</option>';
            $typeHtml .= '<option value="1" ' . ($allowance->type == '1' ? 'selected' : '') . '>Amount</option>';
            $typeHtml .= '<option value="2" ' . ($allowance->type == '2' ? 'selected' : '') . '>Percentage</option>';
            $typeHtml .= '</span>';

            $calculationHtml = '<span>
            <option value="">--Select Calculation--</option>';
            $calculationHtml .= '<option value="1" ' . ($allowance->calculation == '1' ? 'selected' : '') . '>Fixed</option>';
            $calculationHtml .= '<option value="2" ' . ($allowance->calculation == '2' ? 'selected' : '') . '>Dynamic</option>';
            $calculationHtml .= '</span>';

            $response = [
                'result'            => 1,
                'allowance'         => $allowance,
                'typeHtml'          => $typeHtml,
                'calculationHtml'   => $calculationHtml,
            ];
        } else {
            $response = ['result' => 0];
        }
        return $response;
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateAllowanceRequest $request, Allowance $allowance)
    {
        try {
            DB::beginTransaction();
            $input = $request->validated();
            $allowance->update(Arr::only($input, Allowance::getFillables()));
            DB::commit();
            return response()->json(['success' => 'Allowance updated successfully!']);
        } catch (\Exception $e) {
            return $this->respondWithAjax($e, 'updating', 'Allowance');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Allowance $allowance)
    {
        try {
            DB::beginTransaction();
            $allowance->delete();
            DB::commit();
            return response()->json(['success' => 'Allowance deleted successfully!']);
        } catch (\Exception $e) {
            return $this->respondWithAjax($e, 'deleting', 'Allowance');
        }
    }
}

app/Http/Controllers/Admin/Masters/BankController.php
<?php

namespace App\Http\Controllers\Admin\Masters;

use App\Http\Controllers\Admin\Controller;
use Illuminate\Http\Request;
use App\Models\Bank;
use App\Http\Requests\Admin\Masters\StoreBankRequest;
use App\Http\Requests\Admin\Masters\UpdateBankRequest;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;

class BankController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $banks = Bank::latest()->get();

        return view('admin.masters.banks')->with(['banks' => $banks]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreBankRequest $request)
    {
        try {
            DB::beginTransaction();
            $input = $request->validated();
            Bank::create(Arr::only($input, Bank::getFillables()));
            DB::commit();

            return response()->json(['success' => 'Bank created successfully!']);
        } catch (\Exception $e) {
            return $this->respondWithAjax($e, 'creating', 'Bank');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Bank $bank)
    {
        if ($bank) {
            $response = [
                'result' => 1,
                'bank' => $bank,
            ];
        } else {
            $response = ['result' => 0];
        }
        return $response;
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateBankRequest $request, Bank $bank)
    {
        try {
            DB::beginTransaction();
            $input = $request->validated();
            $bank->update(Arr::only($input, Bank::getFillables()));
            DB::commit();

            return response()->json(['success' => 'Bank updated successfully!']);
        } catch (\Exception $e) {
            return $this->respondWithAjax($e, 'updating', 'Bank');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Bank $bank)
    {
        try {
            DB::beginTransaction();
            $bank->delete();
            DB::commit();
            return response()->json(['success' => 'Bank deleted successfully!']);
        } catch (\Exception $e) {
            return $this->respondWithAjax($e, 'deleting', 'Bank');
        }
    }
}

resources/views/admin/masters/departments.blade.php
<x-admin.layout>
    <x-slot name="title">Departments</x-slot>
    <x-slot name="heading">Departments</x-slot>
    {{-- <x-slot name="subheading">Test</x-slot> --}}


    <!-- Add Form -->
    <div class="row" id="addContainer" style="display:none;">
        <div class="col-sm-12">
            <div class="card">
                <header class="card-header">
                    <h4 class="card-title">Add Department</h4>
                </header>
                <form class="theme-form" name="addForm" id="addForm" enctype="multipart/form-data">
                    @csrf

                    <div class="card-body">
                        <div class="mb-3 row">

                            <div class="col-md-4">
                                <label class="col-form-label" for="name">Select Ward<span class="text-danger">*</span></label>
                                <select class="form-control" id="ward" name="ward_id">
                                    <option value="">Select Ward</option>
                                    @foreach ($wards as $ward)
                                        <option value="{{ $ward->id }}">{{ $ward->name }}</option>
                                    @endforeach
                                </select>
                                <span class="text-danger invalid ward_id_err"></span>
                            </div>

                            <div class="col-md-4">
                                <label class="col-form-label" for="name">Department Name <span class="text-danger">*</span></label>
                                <input class="form-control" id="name" name="name" type="text" placeholder="Enter Ward Name">
                                <span class="text-danger invalid name_err"></span>
                            </div>
                            <div class="col-md-4">
                                <label class="col-form-label" for="initial">Initial <span class="text-danger"></span></label>
                                <input class="form-control" id="initial" name="initial" type="text" placeholder="Enter Ward Initial">
                                <span class="text-danger invalid initial_err"></span>
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary" id="addSubmit">Submit</button>
                        <button type="reset" class="btn btn-warning">Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>



    {{-- Edit Form --}}
    <div class="row" id="editContainer" style="display:none;">
        <div class="col">
            <form class="form-horizontal form-bordered" method="post" id="editForm">
                @csrf
                <section class="card">
                    <header class="card-header">
                        <h4 class="card-title">Edit Ward</h4>
                    </header>

                    <div class="card-body py-2">

                        <input type="hidden" id="edit_model_id" name="edit_model_id" value="">
                        <div class="mb-3 row">

                            <div class="col-md-4">
                                <label class="col-form-label" for="name">Select Ward<span class="text-danger">*</span></label>
                                <select class="form-control" id="edit_ward" name="ward_id">
                                    <option value="">Select Ward</option>
                                    @foreach ($wards as $ward)
                                        <option value="{{ $ward->id }}">{{ $ward->name }}</option>
                                    @endforeach
                                </select>
                                <span class="text-danger invalid ward_id_err"></span>
                            </div>

                            <div class="col-md-4">
                                <label class="col-form-label" for="name">Department Name <span class="text-danger">*</span></label>
                                <input class="form-control" id="name" name="name" type="text" placeholder="Ward Name">
                                <span class="text-danger invalid name_err"></span>
                            </div>
                            <div class="col-md-4">
                                <label class="col-form-label" for="initial">Initial <span class="text-danger"></span></label>
                                <input class="form-control" id="initial" name="initial" type="text" placeholder="Enter Ward Initial">
                                <span class="text-danger invalid initial_err"></span>
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <button class="btn btn-primary" id="editSubmit">Submit</button>
                        <button type="reset" class="btn btn-warning">Reset</button>
                    </div>
                </section>
            </form>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                @can('departments.create')
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="">
                                    <button id="addToTable" class="btn btn-primary">Add <i class="fa fa-plus"></i></button>
                                    <button id="btnCancel" class="btn btn-danger" style="display:none;">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                @endcan
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="buttons-datatables" class="table table-bordered nowrap align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Sr No.</th>
                                    <th>Ward Name</th>
                                    <th>Department</th>
                                    <th>Department Initial</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($departments as $department)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $department?->ward?->name }}</td>
                                        <td>{{ $department?->name }}</td>
                                        <td>{{ $department?->initial }}</td>
                                        <td>
                                            @can('departments.edit')
                                                <button class="edit-element btn btn-secondary px-2 py-1" title="Edit ward" data-id="{{ $department->id }}"><i data-feather="edit"></i></button>
                                            @endcan
                                            @can('departments.delete')
                                                <button class="btn btn-danger rem-element px-2 py-1" title="Delete ward" data-id="{{ $department->id }}"><i data-feather="trash-2"></i> </button>
                                            @endcan
                                        </td>
                                    </tr>
                                @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




</x-admin.layout>


{{-- Add --}}
<script>
    $("#addForm").submit(function(e) {
        e.preventDefault();
        $("#addSubmit").prop('disabled', true);

        var formdata = new FormData(this);
        $.ajax({
            url: '{{ route('department.store') }}',
            type: 'POST',
            data: formdata,
            contentType: false,
            processData: false,
            success: function(data) {
                $("#addSubmit").prop('disabled', false);
                if (!data.error2)
                    swal("Successful!", data.success, "success")
                    .then((action) => {
                        window.location.href = '{{ route('department.index') }}';
                    });
                else
                    swal("Error!", data.error2, "error");
            },
            statusCode: {
                422: function(responseObject, textStatus, jqXHR) {
                    $("#addSubmit").prop('disabled', false);
                    resetErrors();
                    printErrMsg(responseObject.responseJSON.errors);
                },
                500: function(responseObject, textStatus, errorThrown) {
                    $("#addSubmit").prop('disabled', false);
                    swal("Error occured!", "Something went wrong please try again", "error");
                }
            }
        });

    });
</script>


<!-- Edit -->
<script>
    $("#buttons-datatables").on("click", ".edit-element", function(e) {
        e.preventDefault();
        var model_id = $(this).attr("data-id");
        var url = "{{ route('department.edit', ':model_id') }}";

        $.ajax({
            url: url.replace(':model_id', model_id),
            type: 'GET',
            data: {
                '_token': "{{ csrf_token() }}"
            },
            success: function(data, textStatus, jqXHR) {
                editFormBehaviour();
                if (!data.error) {
                    $("#editForm input[name='edit_model_id']").val(data.department.id);
                    $("#editForm input[name='name']").val(data.department.name);
                    $("#editForm input[name='initial']").val(data.department.initial);
                    $("#edit_ward").html(data.wardHtml);
                } else {
                    alert(data.error);
                }
            },
            error: function(error, jqXHR, textStatus, errorThrown) {
                alert("Some thing went wrong");
            },
        });
    });
</script>


<!-- Update -->
<script>
    $(document).ready(function() {
        $("#editForm").submit(function(e) {
            e.preventDefault();
            $("#editSubmit").prop('disabled', true);
            var formdata = new FormData(this);
            formdata.append('_method', 'PUT');
            var model_id = $('#edit_model_id').val();
            var url = "{{ route('department.update', ':model_id') }}";
            //
            $.ajax({
                url: url.replace(':model_id', model_id),
                type: 'POST',
                data: formdata,
                contentType: false,
                processData: false,
                success: function(data) {
                    $("#editSubmit").prop('disabled', false);
                    if (!data.error2)
                        swal("Successful!", data.success, "success")
                        .then((action) => {
                            window.location.href = '{{ route('department.index') }}';
                        });
                    else
                        swal("Error!", data.error2, "error");
                },
                statusCode: {
                    422: function(responseObject, textStatus, jqXHR) {
                        $("#editSubmit").prop('disabled', false);
                        resetErrors();
                        printErrMsg(responseObject.responseJSON.errors);
                    },
                    500: function(responseObject, textStatus, errorThrown) {
                        $("#editSubmit").prop('disabled', false);
                        swal("Error occured!", "Something went wrong please try again", "error");
                    }
                }
            });

        });
    });
</script>


<!-- Delete -->
<script>
    $("#buttons-datatables").on("click", ".rem-element", function(e) {
        e.preventDefault();
        swal({
                title: "Are you sure to delete this Department?",
                icon: "info",
                buttons: ["Cancel", "Confirm"]
            })
            .then((justTransfer) => {
                if (justTransfer) {
                    var model_id = $(this).attr("data-id");
                    var url = "{{ route('department.destroy', ':model_id') }}";

                    $.ajax({
                        url: url.replace(':model_id', model_id),
                        type: 'POST',
                        data: {
                            '_method': "DELETE",
                            '_token': "{{ csrf_token() }}"
                        },
                        success: function(data, textStatus, jqXHR) {
                            if (!data.error && !data.error2) {
                                swal("Success!", data.success, "success")
                                    .then((action) => {
                                        window.location.reload();
                                    });
                            } else {
                                if (data.error) {
                                    swal("Error!", data.error, "error");
                                } else {
                                    swal("Error!", data.error2, "error");
                                }
                            }
                        },
                        error: function(error, jqXHR, textStatus, errorThrown) {
                            swal("Error!", "Something went wrong", "error");
                        },
                    });
                }
            });
    });
</script>